name: BucikGenerators
version: 1.0.4
description: A customizable plugin for setting up block generators.
main: pl.workonfire.bucik.generators.Main
api-version: 1.15
authors: [Buty935]
commands:
  generators:
    description: "Main command."
    aliases: [gene, generator]
  drop:
    description: "A command for displaying generator drop details."
    aliases: [genedrop, generatordrop]